package com.yaser.data.model;


import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * TblDistrict generated by hbm2java
 */
@Entity
public class TblDistrict implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue
	private int districtId;
	
	@ManyToOne
	@JoinColumn(name="city_id")
	private TblCity tblCity;	
	private String districtName;
	@OneToMany
	private Set<TblSubdistrict> tblSubdistricts;


	public int getDistrictId() {
		return this.districtId;
	}

	public Set<TblSubdistrict> getTblSubdistricts() {
		return tblSubdistricts;
	}

	public void setTblSubdistricts(Set<TblSubdistrict> tblSubdistricts) {
		this.tblSubdistricts = tblSubdistricts;
	}

	public void setDistrictId(int districtId) {
		this.districtId = districtId;
	}

	public TblCity getTblCity() {
		return this.tblCity;
	}

	public void setTblCity(TblCity tblCity) {
		this.tblCity = tblCity;
	}

	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}
}
