package com.yaser.data.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * TblSubdistrict generated by hbm2java
 */
@Entity
public class TblSubdistrict implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// Fields
	@Id
	private int subdistrictId;
	@ManyToOne
	@JoinColumn(name="district_id")
	private TblDistrict district;
	private String subdistrictName;

	// Constructors


	// Property accessors

	public int getSubdistrictId() {
		return this.subdistrictId;
	}

	public void setSubdistrictId(int subdistrictId) {
		this.subdistrictId = subdistrictId;
	}

	public String getSubdistrictName() {
		return this.subdistrictName;
	}

	public void setSubdistrictName(String subdistrictName) {
		this.subdistrictName = subdistrictName;
	}

	public TblDistrict getDistrict() {
		return district;
	}

	public void setDistrict(TblDistrict district) {
		this.district = district;
	}

}
